<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Siswa_model extends CI_Model
{

    public $table = 'siswa';
    public $id = 'NIS';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('NIS', $q);
	$this->db->or_like('Nama_Siswa', $q);
	$this->db->or_like('Jenis_Kelamin', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Asal_Sekolah', $q);
	$this->db->or_like('Code_Progdi', $q);
	$this->db->or_like('Pembuatan', $q);
	$this->db->or_like('code_pembuat', $q);
	$this->db->or_like('Pembaharuan', $q);
	$this->db->or_like('Code_Pembaharuan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('NIS', $q);
	$this->db->or_like('Nama_Siswa', $q);
	$this->db->or_like('Jenis_Kelamin', $q);
	$this->db->or_like('Alamat', $q);
	$this->db->or_like('Asal_Sekolah', $q);
	$this->db->or_like('Code_Progdi', $q);
	$this->db->or_like('Pembuatan', $q);
	$this->db->or_like('code_pembuat', $q);
	$this->db->or_like('Pembaharuan', $q);
	$this->db->or_like('Code_Pembaharuan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Siswa_model.php */
/* Location: ./application/models/Siswa_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-05-13 12:05:15 */
/* http://harviacode.com */